### ISSUE TITLE
PKM: Bullets fed from the ammobelt bugged

### ISSUE THREAD

**Issue by Furean** [FinModA3/development#10]
**Severity:** Minor

**Description:** When you fire the last bullets of a belt with the PKM, the bullets mysteriously shrink in size and move backwards.

_Steps to reproduce:_ Use PKM in game, and fire a belt until it's empty.

**Additional information:** [Screenshot](http://imgur.com/a/mpGP8)

**Arma 3 version:** 1.64
**Finmod version:** Alpha
**CBA version:** 3.0.0
**Is this a request/wish?:** No

**Comment by troskavi** [comment]
Belt moment and bullets corrected.
