### ISSUE TITLE
RK 95 MG assistant, without PKM cases

### ISSUE THREAD

**Issue by anssirantanen** [FinModA3/development#14]
No PKM cases in inventory.

**Comment by Arskah** [comment]
18:08:51 soldier[fin_MGa_RK95]:Some of magazines weren't stored in soldier Vest or Uniform?
18:08:51 soldier[fin_MGa_RK95]:Some of magazines weren't stored in soldier Vest or Uniform?

Mg assistant has no room in inventory. Need to add backpack for that unit

**Comment by Arskah** [comment]
SHA-1: 571faaf7a079871f3537c812b18efb843bf9a039

**Comment by Arskah** [comment]
MG assistant has backpack and 2 mags in it. Closing
