### ISSUE TITLE
KES 88 sound curve missing

### ISSUE THREAD

**Issue by itZzosku** [FinModA3/development#17]
Title: KES 88 sound curve missing
Add following details: When you place unit with kes 88 error pop up on the screen 

Severity: Major

Description:
Steps to reproduce: Put unit on editor with kes 88 

Additional information:

Arma 3 version: 1.64
Finmod version: alpha
CBA version: 3.0.0
Is this a request/wish?: No

![20160924150652_1](https://cloud.githubusercontent.com/assets/16781987/18808380/2c5f97e0-8269-11e6-90b1-82d62c5e070d.jpg)

**Comment by KuiK** [comment]
Fixed
