### ISSUE TITLE
Icon missing from Glock 17 Mag in inventory

### ISSUE THREAD

**Issue by Furean** [FinModA3/development#2]
**Severity:** Minor

**Description:** The icon is missing from the Glock 17 mags in the inventory.
**Steps to reproduce:** Place a Glock 17 mag to your inventory.

**Additional information:**

**Arma 3 version:** 1.64
**Finmod version:** Alpha
**CBA version:** 3.0.0

**Comment by saunatyyny** [comment]
Fixed

**Comment by saunatyyny** [comment]
Fixed, remove "P:" from start of picture in file FinMod\addons\fin_pistols_c\G17\cfgmagazines.hpp
