### ISSUE TITLE
PKM Boxes floating in the air

### ISSUE THREAD

**Issue by berillis** [FinModA3/development#20]
Title: PKM Boxes floating in the air
Add following details: PKM boxes in the M05 Flak Jacket (PKM) aren't attached to anything and seem to be floating in the air.

Severity: Minor

Description:
Steps to reproduce: Spawn a unit with M05 Flak Jacket (PKM)

![capture](https://cloud.githubusercontent.com/assets/16781849/18873013/0ba627e4-84c6-11e6-88b3-b1650db772b8.JPG)

Additional information:

Arma 3 version: 164
Finmod version: alpha
CBA version:3.0.0
Is this a request/wish?: No

**Comment by saunatyyny** [comment]
Any ideas how to improve this model of PKM gunner's FLAK vest?

**Comment by berillis** [comment]
I'd say just leave the PKM gunners FLAK vest out of the mod, and make them only for the bearing vest versions.

**Comment by saunatyyny** [comment]
Granted

**Comment by saunatyyny** [comment]
Done
