### ISSUE TITLE
RK95 Inventory images switched

### ISSUE THREAD

**Issue by berillis** [FinModA3/development#21]
Title: RK95 Inventory images switched
Add following details:

Severity: Minor
Description:
Steps to reproduce: See RK95 TP in inventory with and without optics.
Additional information:
When the RK95 TP is without optics, the inventory picture shows that the cheekpiece is there, when actually it's not. When the RK95 TP is with optics, the inventory picture shows that the cheekpiece is not there, when it actually is.

![capture](https://cloud.githubusercontent.com/assets/16781849/18873379/dbce1fca-84c7-11e6-8688-417f3e8b099c.JPG)

Arma 3 version: 1,64
Finmod version: alpha
CBA version: 3.0.0
Is this a request/wish?: no

**Comment by Arskah** [comment]
Arma default optic images need to be fixed for RKs, like they are in TRG
