### ISSUE TITLE
Load-Bearing-Vest load size

### ISSUE THREAD

**Issue by castorFIN** [FinModA3/development#23]
Title: Load-Bearing-Vest load size
Add following details:

Severity: Minor
Description:
Steps to reproduce: See Any load-bearing-vest
Additional information:
The load bearing vest visually only has enough carrying capacity for 6 RK mags and a couple of grenades, at the moment the vest can carry 10 RK mags which is way too much.

Arma 3 version: 1,64
Finmod version: alpha
CBA version: 3.0.0
Is this a request/wish?: no

**Comment by Arskah** [comment]
Fixed and will be updated to testing for comments
