### ISSUE TITLE
APILAS front cover too small

### ISSUE THREAD

**Issue by Rygelius** [FinModA3/development#25]
**Severity:** Minor

**Description:** Apilas front cover (Etukansi) too "high" and too small, see pictures for reference. Very small gripe but visually distinctive when carried in soldiers back like that.

**Steps to reproduce:** View any soldier with APILAS on their back on editor or game.

**Additional information:** 
Comparison in game and irl: 
In game: http://imgur.com/a/QzkrU
IRL: http://tonnel-ufo.ru/foto/oruhie/granata_2/france/apilas.jpg
http://www.plutoona.mpoli.fi/nuoli2001/album/images/IM000524.jpg

Arma 3 version: 1.64
Finmod version: Alpha
CBA version: 3.0.0
Is this a request/wish?: No

**Comment by Arskah** [comment]
To be checked if simple OB editing fixes issue

**Comment by troskavi** [comment]
FIXED: Scaled front cover up.
