### ISSUE TITLE
Mem points for legs are incorrect on the uniform 

### ISSUE THREAD

**Issue by Furean** [FinModA3/development#27]
Severity: Major

Description: The memory points on the uniform can be found below the ground when attempting to use the medic system in ACE.

Steps to reproduce: Look at the legs with ace interaction system on another player / ai wearing the uniform in the game.

Additional information: http://imgur.com/a/ZVCqm

Arma 3 version: 1.64
Finmod version: Alpha
CBA version: 3.0.0
Is this a request/wish?: No

**Comment by Arskah** [comment]
Updated major

**Comment by itZzosku** [comment]
Fixed
can be resolved and closed. Thanks to furean for reporting.
