### ISSUE TITLE
Uniform clips through M05 Load Bearing Vest

### ISSUE THREAD

**Issue by berillis** [FinModA3/development#28]
Severity: Minor

Description: Uniform clips through M05 Load Bearing Vest when observed from 10m+
Steps to reproduce: View any soldier with M05 Load Bearing Vest from a distance greater than 10m.

Additional information: 
Picture:
![capture](https://cloud.githubusercontent.com/assets/16781849/18948545/32b50abe-8640-11e6-8776-064db5da15f2.JPG)

Arma 3 version: 1.64
Finmod version: Alpha
CBA version: 3.0.0
Is this a request/wish?: No

**Comment by Arskah** [comment]
To be checked if clips with other LODs as well
