### ISSUE TITLE
RK 62; has no mass

### ISSUE THREAD

**Issue by BargoAFI** [FinModA3/development#29]
RK 62 currently weighs 0.0 kg.

Tested on AFI server and editor.

**Comment by saunatyyny** [comment]
Need more info. Can you please fill full bugfreport and tell if this still exits with and without ACE 3?

**Comment by BargoAFI** [comment]
Severity: Minor

Description:
Inventory shows that Rk 62 weighs 0.0kg. Tested with ACE since vanilla does not show gear weight in inventory.
![image](https://cloud.githubusercontent.com/assets/22505532/18992630/0e74fa0e-8728-11e6-8749-fe30c7b7d424.png)

Steps to reproduce:
Launch game with cba, finmod and ace. Select unit with rk62 and drop all gear besides rk62.

Additional information:
        Arma 3 version: 1.64
        Finmod version: Alpha(?)
        CBA version: 3.0

**Comment by itZzosku** [comment]
resolved. can be closed
