### ISSUE TITLE
Right arm narrows when riding on truck with RK-62/RK-95

### ISSUE THREAD

**Issue by Jacali18** [FinModA3/development#32]
Right arm narrows on rifleman with RK-62 / RK-95 when riding aboard  M1078A1P2-B (RHS USFS mod). 

![20160929162320_1](https://cloud.githubusercontent.com/assets/22522657/18955969/4a6c8d90-8662-11e6-912c-e8de6eb89830.jpg)

**Comment by saunatyyny** [comment]
This issue is caused by RHS vehicle's sitting RTM file. We will take a look if anything can be done about it.
