### ISSUE TITLE
Grenade pouch model jumps off of the M05 load-bearing vest

### ISSUE THREAD

**Issue by Rygelius** [FinModA3/development#34]
**Severity:**

**Description:** The newly added grenade pouch drops to the ground and casts a weird shadow when viewed from distance of 5-10 meters from the soldier.

**Steps to reproduce:** Place unit with any M05 load-bearing vest variation. Move away from the unit (5-10 meters) and the model of the pouch moves and a shadow appears.

**Additional information:** http://imgur.com/a/o71Mg

**Arma 3 version:** 1.64
**Finmod version:** Alpha (2nd Oct version)
**CBA version:** 3.1.0
**ACE3:** 3.7.0
**Is this a request/wish?:** No

**Comment by saunatyyny** [comment]
Pouch has been removed for now
