### ISSUE TITLE
ACOG lens problems

### ISSUE THREAD

**Issue by Arskah** [FinModA3/development#38]
http://images.akamai.steamusercontent.com/ugc/248088330054762902/B847DE44C8D48AAFF693A081DC84915C9D9202F4/

Seems to occur when aiming dark textures

http://images.akamai.steamusercontent.com/ugc/248088330054796298/06139736114F4AE7ADED13B9B0D8FF5A99589556/
http://images.akamai.steamusercontent.com/ugc/248088330054796467/E6E7457DFCB52AF680A7AFB6F9D21F430ECB57C9/
http://images.akamai.steamusercontent.com/ugc/248088330054796589/D2C522703DE432AF0CBF7F05A2B4BC09E85D5103/

**Comment by saunatyyny** [comment]
Disable Depth of field from Arma 3 graphic settings.

**Comment by troskavi** [comment]
Problem with BI graphic setting. 
Some ppl are experiencing similar problems with vanilla sights.
We have also added 2D sight as second alternative.
