### ISSUE TITLE
112 RsKES APILAS generates magazines to inventory while shooting.

### ISSUE THREAD

**Issue by castorFIN** [FinModA3/development#45]
Severity: Severe

Description: Shooting 112 RsKES APILAS will result 17 112 RsKES APILAS magazines appearing in your vest inventory.

Steps to reproduce: Equip 112 RsKES APILAS and shoot it.

Arma 3 version: 1.72
Finmod version: Alpha
CBA version: 3.4.0.170627
Is this a request/wish?: No

**Comment by Arskah** [comment]
Locality issue with FinMod disposable launchers. Added quick local check up inside the script.

SHA-1: b49d6a74dc548c7a1281cf4f76482798d61895bc

* Add locality check to disposable reload script

Close if fixed in AFI hotfix release

**Comment by Arskah** [comment]
No problems encountered in testing, closing.
