### ISSUE TITLE
Cannot use LISA while wearing a FinMod Launcher

### ISSUE THREAD

**Issue by castorFIN** [FinModA3/development#46]
Severity: Severe

Description: While carrying FinMod Launchers you cannot use LISA

Steps to reproduce: Equip a Finmod launcher and try to use LISA

Arma 3 version: 1.72
Finmod version: Alpha
CBA version: 3.4.0.170627
Is this a request/wish?: No

**Comment by Arskah** [comment]
Problem also with any binocular etc. object that becomes "primaryWeapon" on switch.

Bug fixed in commit 

SHA-1: 78e82d0b703eb8d6c44513ed76636eadc0392263

* Fix bug #46
