### ISSUE TITLE
RK62 is too light

### ISSUE THREAD

**Issue by castorFIN** [FinModA3/development#47]
Severity: Minor

Description: RK62 weight is too low, it is about 1/5 the weight of RK95.

Steps to reproduce: Equip RK62 in virtual arsenal.

Arma 3 version: 1.72
Finmod version: Alpha
CBA version: 3.4.0.170627
Is this a request/wish?: No

**Comment by Arskah** [comment]
Fixed in commit 

SHA-1: 16d50a06a6ba41523eeaf455924c3086120d0e05

* Fix Bug #47: RK62 is too light

Mass was not defined inside class WeaponSlotsInfo
