### ISSUE TITLE
PKM iron sight zeroing broken

### ISSUE THREAD

**Issue by saunatyyny** [FinModA3/development#48]
Severity: Minor

    Description: PKM zeroing animation doesn't adjust the front sight, only raises eye point from mem lod

    Steps to reproduce: Zero with PKM without any scope

    Additional information:
        Arma 3 version: 1.72
        Finmod version Alpha v3
        CBA version: 3.4.0

    Is this a request/wish?: No

**Comment by troskavi** [comment]
Sight movement fixed
