### ISSUE TITLE
Respawning with RK95 with aimpoint gives error and weapon disappears

### ISSUE THREAD

**Issue by Nyyppis** [FinModA3/development#49]
This error occurs only in editor when testing mission with Multiplayer mode and only after respawning.

Every time I respawn with RK95 that is equipped with PP2009 or PP2004 (fin_rk95_aimpoint), I get an error and my gun disappears from my invetory.

Picture of the error with PP2004: http://i.imgur.com/KtKhTtG.png

Steps to reproduce:
1. Create mission with custom respawn positions
2. Put player unit from FinMod with aimpoint (PP2009, PP2004)
3. Start mission with multiplayer in editor
4. Respawn on the field and watch as your weapon disappears.

**Comment by Arskah** [comment]
Need to fix configs in cfgUnits.cpp. Some units have bad respawnWeapons entries

**Comment by Arskah** [comment]
Fixed in commit
SHA-1: bfe34385b3c57cda4936ebdb3b7fd51801b2c740
