### ISSUE TITLE
Flakvest models shouldn't have DAPS installed

### ISSUE THREAD

**Issue by Blahus** [FinModA3/development#54]
Hartiasuojat pitäisi olla sirpaleliivimalleista pois. DAPSit jaetaan vain luotisuojamallin mukana.

Lisäksi dapsit ylipäätänsä on tarkoitettu lähinnä ajoneuvon tornimiehelle. Näyttävät vähän hölmöltä perus JVlla.

**Comment by Arskah** [comment]
Fixed in commits
f08fd78a9f85ff21b891736f897d00e75239cb85
15f5f0d623df4e36c41ad1dd99daf31f499033b6
