### ISSUE TITLE
PKM: Ironsights not aligned when changing zeroing

### ISSUE THREAD

**Issue by Furean** [FinModA3/development#8]
Severity: Minor

Description: When you change the zeroing on the PKM, the ironsights isn't aligned.

Steps to reproduce: Use PKM in game, and change zeroing.

Additional information: [Screenshot](http://imgur.com/a/5m2cT)

Arma 3 version: 1.64
Finmod version: Alpha
CBA version: 3.0.0
Is this a request/wish?: No

**Comment by troskavi** [comment]
FIXED: Zeroing added for PKM ironsights.
