### ISSUE TITLE
RK95 TP with acog  + inventory bug (updated)

### ISSUE THREAD

**Issue by anssirantanen** [FinModA3/development#9]
![dmr_reload_inventory_bug](https://cloud.githubusercontent.com/assets/12626304/18798322/a735d3ba-81da-11e6-9fbe-e35c2a3f5be9.png)

Comes up when trying to access inventory while reload animation running.

**Comment by anssirantanen** [comment]
Isolated issue into rk-95 tp with acog. RDS PP2009 doesn't trigger bug.

**Comment by Arskah** [comment]
Send me a pic from inside inventory. I think ACOG picture is missing.

Fixed in release branch, closing after symptom is confirmed.
SHA-1: 57a3d9f8c6ea32194169aa6407929d5ba17e1729
